name: Publish Package

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  publish:
    name: Publish
    needs: lint

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish package
      run: npm publish --access public